workflow:
  Prompter:
    description: Format tasks for API request
    responsible_department: INTEGRATION
    action:
      type: class_execution
      class: PrompterAgent
      module: Vincius.Agents.Prompter.agent
      input_key: null
      output_key: prompt_output
      agent_config:
        model: "gemini-2.0-flash"
        max_tokens: 1024
        temperature: 0.7
        prompt: "Format the following tasks into a JSON array suitable for an API request: {tasks_result}"
    next_steps:
      success_step: APIRequest
