workflow:
  Analysis:
    description: "Analyze and document the requirements for the software."
    responsible_department: ANALYSIS
    action:
      type: class_execution
      class: AnalystAgent
      module: Vincius.Agents.Analyst.agent
      input_key: null
      output_key: analysis_result
      agent_config:
        base_dir_key: "Docs"
        prompt: "Escreva os requerimentos para criar um site em html com 3 paginas, home, experiencies e sobre. Escolha o conteudo o as paginas deve ter um design moderno usando o tailwind"
        model: "gemini-2.0-flash"
        max_tokens: 1024
        temperature: 0.7
        debug_mode: true
        guidelines:
          - "Focus on system architecture and components"
          - "Consider scalability and maintainability"
          - "Identify potential technical challenges"
          - "Document all technical requirements clearly"
          - "Provide clear implementation recommendations"
    next_steps:
      success_step: Development

  Development:
    description: "Develop the software based on the analyzed requirements."
    responsible_department: DEVELOPMENT
    action:
      type: class_execution
      class: DeveloperAgent
      module: Vincius.Agents.Developer.agent
      input_key: analysis_result
      output_key: development_output
      agent_config:
        base_dir_key: "Codebase"
        model: "gemini-2.0-flash"
        max_tokens: 2048
        temperature: 0.9
        prompt: "Based on the technical analysis, implement the the html pages usign modern design with tailwind."
        guidelines:
          - "Develop using a clean html"
          - "HTML and CSS"
          - "Tailwind"
          - "Modern Design"
          - "Implement error handling"
          - "Write clean, maintainable code"
    next_steps:
      success_step: {}
