workflow:
  APIRequest:
    description: Create and format API requests based on input data
    responsible_department: INTEGRATION
    action:
      type: class_execution
      class: APIRequestAgent
      module: Vincius.Agents.APIRequest.agent
      input_key: null
      output_key: api_request_result
      agent_config:
        base_dir_key: "API"
        method: "GET"
        api_config:
          base_url: "https://run.mocky.io/v3/ce6eb924-5ea9-4eeb-a00e-1996dd1c0690"
    next_steps:
      success_step: {}
