workflow:
  Development:
    description: Develop the software based on the analyzed requirements.
    responsible_department: DEVELOPMENT
    action:
      type: class_execution
      class: DeveloperAgent
      module: Vincius.Agents.Developer.agent
      input_key: analysis_result
      output_key: development_output
      agent_config:
        model: "gemini-2.0-flash"
        max_tokens: 2048
        temperature: 0.9
        prompt: "Criar uma página inicial (home) para o GitScrum usando Tailwind CSS pode ser uma tarefa interessante. O GitScrum é uma ferramenta de gerenciamento ágil que combina os conceitos do GitHub e Scrum, então a página home deve refletir isso com um design moderno, limpo e profissional."
        guidelines:
          - "Develop using a clean html"
          - "HTML and CSS"
          - "Tailwind"
          - "Modern Design"
          - "Responsive Design"
          - "nome da pagina deve ser index.html"
    next_steps:
      success_step: Development2
  Development2:
    description: Develop the software based on the analyzed requirements.
    responsible_department: DEVELOPMENT
    action:
      type: class_execution
      class: DeveloperAgent
      module: Vincius.Agents.Developer.agent
      input_key: null
      output_key: development_output
      agent_config:
        model: "gemini-2.0-flash"
        max_tokens: 2048
        temperature: 0.9
        prompt: "Criar uma página de precos (pricing) para o GitScrum usando Tailwind CSS pode ser uma tarefa interessante. O GitScrum é uma ferramenta de gerenciamento ágil que combina os conceitos do GitHub e Scrum, então a página de precificacao para refletir isso com um design moderno, limpo e profissional."
        guidelines:
          - "Pagina de preco"
          - "HTML and CSS"
          - "Tailwind"
          - "Modern Design"
          - "Responsive Design"
          - "nome a pagina deve ser pricing.html"
    next_steps:
      success_step: {}
